### ISSUE TITLE
Having a `Requirements.txt` would be useful

### ISSUE THREAD

**Issue by kibanez** [oscarlr-TRs/EH-expansion-evaluator#3]
Hello, 

I've cloned your repo and created a virtual environment. I'm missing some requirements.txt file to have explicit python libraries that the repo uses.

So everyone can include in the venv the modules required by EH-expansion-evaluator.

numpy
pandas
sklearn

In this way anyone can create a virtual environment and install automatically all required packages:

pip install -r requirements.txt

Thanks!

:)

**Comment by oscarlr** [comment]
Thanks for the input! I added the python library requirements to the README.
